apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helm/nginx-deployment
    repoURL: https://github.com/Dobuzi/argocd_ex
    targetRevision: HEAD
